services:
  tor:
    build:
      context: .
      dockerfile: Dockerfile.tor
    restart: always
    scale: ${TOR_REPLICAS:-10}
    deploy:
      resources:
        limits:
          cpus: '0.10'
          memory: 128M
        reservations:
          cpus: '0.01'
          memory: 64M
    volumes:
      - ./torrc:/etc/tor/torrc:ro

  secure-proxy:
    build: .
    container_name: proxy_manager
    restart: unless-stopped
    ports:
      - "8443:8443"
    depends_on:
      - tor
    environment:
      - PYTHONPATH=/app
    volumes:
      - ./filter_plugin.py:/app/filter_plugin.py:ro
    command: >
      proxy
      --hostname 0.0.0.0
      --port 8443
      --plugins filter_plugin.DomainFilterPlugin
      --plugins proxy.plugin.ProxyPoolPlugin
      --proxy-pool http://tor:8118
