services:
  tor:
    image: dperson/torproxy
    container_name: tor_proxy
    restart: unless-stopped
    environment:
      - TOR_MaxCircuitDirtiness=120
      - TOR_NewCircuitPeriod=30
    ports:
      - "127.0.0.1:9052:9050"
      - "127.0.0.1:8118:8118"

  secure-proxy:
    build: .
    container_name: proxy_manager
    restart: unless-stopped
    network_mode: "host" # برای پرفورمنس بهتر و دریافت آی‌پی واقعی کلاینت‌ها
    depends_on:
      - tor
    environment:
      - PYTHONPATH=/app
    volumes:
      # متصل کردن گواهینامه‌های SSL (فقط خواندنی)
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - ./filter_plugin.py:/app/filter_plugin.py:ro
    command: >
      proxy
      --hostname 0.0.0.0
      --port 8443
      --key-file /etc/letsencrypt/live/p.exitlagplus.ir/privkey.pem
      --cert-file /etc/letsencrypt/live/p.exitlagplus.ir/fullchain.pem
      --plugins filter_plugin.DomainFilterPlugin
      --plugins proxy.plugin.ProxyPoolPlugin
      --proxy-pool http://127.0.0.1:8118

